apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: sample-nodejs-app
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/tmadore-tenant/sample-nodejs-app/sample-nodejs-app@sha256:3fc132fe93a058a93e0ef6b88c926b644bb7a992bd10ea1bfe3ff289c31e85e1
        name: container-image
        resources: {}
status: {}
